apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: proxies.space.digi.dev
spec:
  group: space.digi.dev
  names:
    kind: Proxy
    listKind: ProxyList
    plural: proxies
    singular: proxy
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              meta:
                properties:
                  dspace_name:
                    type: string
                  registry_endpoint:
                    type: string
                  user_name:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
